import { z } from "zod";

export const REASON_CODES = [
  "OXRAIL_HOST_ROUTE_UNPROVEN",
  "OXRAIL_HOST_PROFILE_STALE",
  "OXRAIL_REDUNDANT_ACTION",
  "OXRAIL_STALE_TARGET",
  "OXRAIL_NO_PROGRESS",
  "OXRAIL_OBSERVATION_BUDGET",
  "OXRAIL_HUMAN_BOUNDARY",
  "OXRAIL_USER_LEASE_ACTIVE",
  "OXRAIL_CREDENTIAL_FENCE_BLOCKED",
  "OXRAIL_UNSAFE_ORIGIN",
  "OXRAIL_VERIFICATION_INCONCLUSIVE",
  "OXRAIL_RECOVERY_EXHAUSTED",
  "OXRAIL_NATIVE_FIDELITY_FAILED",
  "OXRAIL_CONTROL_CRITICAL_UNKNOWN",
  "OXRAIL_NORMAL_ACTION_PASSTHROUGH",
  "OXRAIL_POST_HANDOFF_TARGET_INVALIDATED",
] as const;

export const ReasonCodeSchema = z.enum(REASON_CODES);
export type ReasonCode = z.infer<typeof ReasonCodeSchema>;
